name = input("What is your name? ")
age = input("How old are you? ")
hobby = input("What is your favorite hobby? ")
city = input("Which city are you from? ")

print("\n🎉 Welcome", name, "! 🎉")
print(f"You are {age} years old.")
print(f"You love {hobby}.")
print(f"You are from {city}.")
print("Nice to meet you!")
